# Gauss-Jordan Elimination
## Elementary Row Operations

In [3]:
import numpy as np

In [20]:
a = np.array([0, 1, 3, 4, -1, 2, 0, 3, 2, -3, 4, 1]).reshape(3, 4)
print(f"a:\n{a}")
print("\n---")
print(f"a R1 & R2:\n{a[[0, 1]]}")
a[[0, 1]] = a[[1, 0]] # A Swap R1 <-> R2
print("===")
print(f"a R1 <-> R2:\n{a}")

a:
[[ 0  1  3  4]
 [-1  2  0  3]
 [ 2 -3  4  1]]

---
a R1 & R2:
[[ 0  1  3  4]
 [-1  2  0  3]]
===
a R1 <-> R2:
[[-1  2  0  3]
 [ 0  1  3  4]
 [ 2 -3  4  1]]


In [29]:
b = np.array([
    [2, -4, 6, -2],
    [1, 3, -3, 0],
    [5, -2, 1, 2]
])
print(f"b:\n{b}")
print("\n---")
print(f"b (1/2)R1:\n{b[[0]] * (1/2)}") 
print("===")
b[[0]] = b[[0]] * (1/2) # B method (1/2)R1 -> R1
print(f"b (1/2)R1 -> R1:\n{b}")

b:
[[ 2 -4  6 -2]
 [ 1  3 -3  0]
 [ 5 -2  1  2]]

---
b (1/2)R1:
[[ 1. -2.  3. -1.]]
===
b (1/2)R1 -> R1:
[[ 1 -2  3 -1]
 [ 1  3 -3  0]
 [ 5 -2  1  2]]


In [37]:
c = np.array([
    [1, 2, -4, 3],
    [0, 3, -2, -1],
    [2, 1, 5, -2]
])
print(f"c:\n{c}")
print("\n---")
print(f"c (-2)R1:\n{c[[0]] * -2}")
print("===")
c[[2]] = c[[2]] + c[[0]] * (1/2) # C method R3 + (-2)R1 -> R3
print(f"c R3 + (-2)R1 -> R3:\n{c}")

c:
[[ 1  2 -4  3]
 [ 0  3 -2 -1]
 [ 2  1  5 -2]]

---
c (-2)R1:
[[-2 -4  8 -6]]
===
c R3 + (-2)R1 -> R3:
[[ 1  2 -4  3]
 [ 0  3 -2 -1]
 [ 2  2  3  0]]


## Page 20
Using Elementary Row Operations to Solve a System

In [7]:
import numpy as np

In [67]:
aam = np.array([
    [1, -2, 3, 9],
    [-1, 3, 0, -4],
    [2, -5, 5, 17]
])
print(f"aam:\n{aam}\n")

display_text = False

aam[[1]] = aam[[1]] + aam[[0]]
# print(f"aam R2 + R1 -> R2:\n{aam}\n" * display_text)

aam[[2]] = aam[[2]] + (-2 * aam[[0]])
# print(f"aam R3 + (-2)R1 -> R3:\n{aam}\n" * display_text)

aam[[2]] = aam[[2]] + aam[[1]]
# print(f"aam R3 + R2 -> R3:\n{aam}\n" * display_text)

aam[[2]] = aam[[2]] * (1/2)
# print(f"aam (1/2)R3 -> R3:\n{aam}\n" * display_text)

aam_m, aam_n = np.split(aam, [3], axis=1)
print("result ordered:\n", aam_m, "\n", aam_n)

aam_cram = aam_m.copy()
aam_i = aam_n.flatten()

aam_result = np.zeros(aam_cram.shape[1], dtype=int)
for i in range(aam_cram.shape[1] - 1, -1, -1):
    print('--j')
    aam_result[i] = aam_i[i] - np.sum(aam_cram[i, i+1:])
    aam_cram[:, i] = aam_cram[:, i] * aam_result[i]
    print(aam_cram)

print(aam_result)


aam:
[[ 1 -2  3  9]
 [-1  3  0 -4]
 [ 2 -5  5 17]]

result ordered:
 [[ 1 -2  3]
 [ 0  1  3]
 [ 0  0  1]] 
 [[9]
 [5]
 [2]]
--j
[[ 1 -2  6]
 [ 0  1  6]
 [ 0  0  2]]
--j
[[ 1  2  6]
 [ 0 -1  6]
 [ 0  0  2]]
--j
[[ 1  2  6]
 [ 0 -1  6]
 [ 0  0  2]]
[ 1 -1  2]


In [ ]:



aam_result = np.zeros(aam_cram.shape[1], dtype=int)
for i in range(aam_cram.shape[1] - 1, -1, -1):
    print('--j')
    aam_result[i] = aam_i[i] - np.sum(aam_cram[i, i+1:])
    aam_cram[:, i] = aam_cram[:, i] * aam_result[i]
    print(aam_cram)

print(aam_result)