In [4]:
import numpy as np
a = np.array([
    [1, 2, 1, -7],
    [2, -2, -2, 8],
    [-1, 3, 4, -8]
])
print(f"a:\n {a}\n")

# a[[1]] = a[[1]] * (1/2)
# print(f"a (1/2)R2:\n {a}\n")

# a[[1]] = a[[1]] + a[[0]]
# print(f"a R2 + R1 -> R2:\n {a}\n")

a[[1]] = a[[1]] + (a[[0]] * -2)
print(f"a R2 + R1 -> R2:\n {a}\n")

a[[2]] = a[[2]] + a[[0]]
print(f"a R3 + R1 -> R3:\n {a}\n")

a[[1]] = a[[2]] + a[[1]]
print(f"a R2 + R1 -> R2:\n {a}\n")

a[[1]] = a[[1]] * -1
print(f"a R3 -> R3:\n {a}\n")

a[[2]] = a[[2]] + (a[[1]] * -5)
print(f"a R3 + R2 -> R3:\n {a}\n")

a[[2]] = a[[2]] * (1/10)
print(f"a R3 -> R3:\n {a}\n")

a:
 [[ 1  2  1 -7]
 [ 2 -2 -2  8]
 [-1  3  4 -8]]

a R2 + R1 -> R2:
 [[ 1  2  1 -7]
 [ 0 -6 -4 22]
 [-1  3  4 -8]]

a R3 + R1 -> R3:
 [[  1   2   1  -7]
 [  0  -6  -4  22]
 [  0   5   5 -15]]

a R2 + R1 -> R2:
 [[  1   2   1  -7]
 [  0  -1   1   7]
 [  0   5   5 -15]]

a R3 -> R3:
 [[  1   2   1  -7]
 [  0   1  -1  -7]
 [  0   5   5 -15]]

a R3 + R2 -> R3:
 [[ 1  2  1 -7]
 [ 0  1 -1 -7]
 [ 0  0 10 20]]

a R3 -> R3:
 [[ 1  2  1 -7]
 [ 0  1 -1 -7]
 [ 0  0  1  2]]



In [6]:
aam_m, aam_n = np.split(a, [3], axis=1)
print("result ordered:\n", aam_m, "\n", aam_n)

aam_cram = aam_m.copy()
aam_i = aam_n.flatten()

aam_result = np.zeros(aam_cram.shape[1], dtype=int)
for i in range(aam_cram.shape[1] - 1, -1, -1):
    print('--j')
    aam_result[i] = aam_i[i] - np.sum(aam_cram[i, i+1:])
    aam_cram[:, i] = aam_cram[:, i] * aam_result[i]
    print(aam_cram)

print(aam_result)

result ordered:
 [[ 1  2  1]
 [ 0  1 -1]
 [ 0  0  1]] 
 [[-7]
 [-7]
 [ 2]]
--j
[[ 1  2  2]
 [ 0  1 -2]
 [ 0  0  2]]
--j
[[  1 -10   2]
 [  0  -5  -2]
 [  0   0   2]]
--j
[[  1 -10   2]
 [  0  -5  -2]
 [  0   0   2]]
[ 1 -5  2]


In [49]:
b = np.array([
    [1, 0, -3, 2],
    [3, 1, -2, -5],
    [2, 2, 1, -4]
])


b[[1]] = b[[1]] + (b[[0]] * -3)
print(f"b (1/3)R1:\n{b}\n")

b[[2]] = b[[2]] + (b[[0]] * -1)
print(f"b (1/3)R2:\n{b}\n")

b[[2]] = b[[2]] + (b[[1]] * -2)
print(f"b (1/3)R3:\n{b}\n")

b[[2]] = b[[2]] + (b[[0]] * -1)
print(f"b (1/3)R4:\n{b}\n")

b[[2]] = b[[2]] * (-1/7)
print(f"b (1/3)R4 -> R4:\n{b}\n")

b (1/3)R1:
[[  1   0  -3   2]
 [  0   1   7 -11]
 [  2   2   1  -4]]

b (1/3)R2:
[[  1   0  -3   2]
 [  0   1   7 -11]
 [  1   2   4  -6]]

b (1/3)R3:
[[  1   0  -3   2]
 [  0   1   7 -11]
 [  1   0 -10  16]]

b (1/3)R4:
[[  1   0  -3   2]
 [  0   1   7 -11]
 [  0   0  -7  14]]

b (1/3)R4 -> R4:
[[  1   0  -3   2]
 [  0   1   7 -11]
 [  0   0   1  -2]]



In [50]:
aam_m, aam_n = np.split(b, [3], axis=1)
print("result ordered:\n", aam_m, "\n", aam_n)

aam_cram = aam_m.copy()
aam_i = aam_n.flatten()

aam_result = np.zeros(aam_cram.shape[1], dtype=int)
for i in range(aam_cram.shape[1] - 1, -1, -1):
    print('--j')
    aam_result[i] = aam_i[i] - np.sum(aam_cram[i, i+1:])
    aam_cram[:, i] = aam_cram[:, i] * aam_result[i]
    print(aam_cram)

print(aam_result)

result ordered:
 [[ 1  0 -3]
 [ 0  1  7]
 [ 0  0  1]] 
 [[  2]
 [-11]
 [ -2]]
--j
[[  1   0   6]
 [  0   1 -14]
 [  0   0  -2]]
--j
[[  1   0   6]
 [  0   3 -14]
 [  0   0  -2]]
--j
[[ -4   0   6]
 [  0   3 -14]
 [  0   0  -2]]
[-4  3 -2]


In [7]:
import logging

logging.basicConfig(level=logging.INFO)
logging.info('This is a debug message')