# Matrices
Outline
- Definition of a Matrix
- Matrix Addition
- Scalar Multiplication
- Matrix Multiplication
- The Transpose of a Matrix

*better use with slides PDF*

we calculate for this MFIT using **numpy**

In [15]:
import numpy as np
import math

## Definition of a Matrix

Each matrix has the indicated size

Size: $1 \times 1$

In [16]:
a = np.array([1])
print("(a) Size: 1*1:", a.shape)

(a) Size: 1*1: (1,)


Size: $2 \times 2$

In [17]:
b = np.array([
    [0, 0],
    [0, 0]
])
print("(b) Size: 2*2:", b.shape)

(b) Size: 2*2: (2, 2)


Size: $1 \times 4$

In [18]:
c = np.array([
    [1, -3, 0, 1/2]
])
print("(c) Size: 3*3:", c.shape)

(c) Size: 3*3: (1, 4)


Size: $3 \times 2$

You can contain any math expression here. but don't worry here much

In [19]:
d = np.array([
    [math.e, math.pi],
    [2, math.sqrt(2)],
    [-7, 4]
])
print("(d) Size: 3*2:", d.shape)

(d) Size: 3*2: (3, 2)


We will get:
$
\begin{bmatrix}
e & \pi \\
2 & \sqrt{2} \\
-7 & 4 
\end{bmatrix}
$

is $3 \times 2$

## Operator with Matrices

- Matrix Addition
- Scalar Multiplication
- Matrix Multiplication
- The Transpose of a Matrix

### Matrix Addition


In [25]:
# (a)
print(
np.array([
    [-1, 2],
    [0, 1]
])
+
np.array([
    [1, 3],
    [-1, 2]
])
)

[[ 0  5]
 [-1  3]]


In [26]:
# (b)
# with save in variables
a = np.array([
    [0, 1, -2],
    [1, 2, 3]
])
b = np.array([
    [0, 0, 0],
    [0, 0, 0],
])
print(a + b)

[[ 0  1 -2]
 [ 1  2  3]]


In [27]:
# (c)
a = np.array([
    [1],
    [-3],
    [-2]
])
b = np.array([
    [-1],
    [3],
    [2]
])
print(a + b)

[[0]
 [0]
 [0]]


In [52]:
# (d)
a = np.array([
    [2, 1, 0],
    [4, 0, -1],
    [3, -2, 2],
])
b = np.array([
    [0, 1],
    [-1, 3],
    [2, 4],
])
try:
    print(a + b)
except ValueError as e:
    print("ERROR!:",e)

ERROR!: operands could not be broadcast together with shapes (3,3) (3,2) 


Error because "a" can't addition with "b"

### Scalar Multiplication

In [29]:
A = np.array([
    [1, 2, 4],
    [-3, 0, -1],
    [2, 1, 2]
])

B = np.array([
    [2, 0, 0],
    [1, -4, 3],
    [-1, 3, 2]
])

In "numpy" you can use it easily

In [32]:
# 3A - B:
print("3A - B:\n", 3*A - B)

3A - B:
 [[  1   6  12]
 [-10   4  -6]
 [  7   0   4]]


$3A - B = 3A + (-B)$

If we try to separate it out

In [48]:
# 3A
c1 = 3*A
print("3A:\n", c1)

# -B
c2 = -B
print("\n-B:\n", c2)

# 3A - B
print("\n3A + (-B):\n", c1 + c2)

3A:
 [[ 3  6 12]
 [-9  0 -3]
 [ 6  3  6]]

-B:
 [[-2  0  0]
 [-1  4 -3]
 [ 1 -3 -2]]

3A + (-B):
 [[  1   6  12]
 [-10   4  -6]
 [  7   0   4]]


Compare between 1 & 2

In [50]:
print("3A - B:\n", 3*A - B)
print("\n3A + (-B):\n", c1 + c2)

print("\n3A - B == 3A + (-B):\n", 3*A - B == c1 + c2)

3A - B:
 [[  1   6  12]
 [-10   4  -6]
 [  7   0   4]]

3A + (-B):
 [[  1   6  12]
 [-10   4  -6]
 [  7   0   4]]

3A - B == 3A + (-B):
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


### Matrix Multiplication

In [55]:
A = np.array([
    [-1, 3],
    [4, -2],
    [5, 0]
])
B = np.array([
    [-3, 2],
    [-4, 1]
])

I "numpy" we can use Matrix Multiplication by using "dot"

    
    

In [59]:
print(np.dot(A, B))

[[ -9   1]
 [ -4   6]
 [-15  10]]


or simplify to @

$A \times B = A @ B$

In [57]:
print(A @ B)

[[ -9   1]
 [ -4   6]
 [-15  10]]


1. check if both matrix can make
**Matrix Multiplication**

columns A = rows B

In [62]:
print(A.shape, B.shape)
print(A.shape[1] == B.shape[0])

(3, 2) (2, 2)
True


2. then will product to original or new size of Matrix

rows A $\times$ columns B 
or (A, B)

In [66]:
print(A.shape, B.shape)
print("Size: ", A.shape[0], "*", B.shape[1])
print((A @ B).shape)

(3, 2) (2, 2)
Size:  3 * 2
(3, 2)
